#' Remove scenarios computed by models with a 2050 time horizon
#' 
#' Use the scenario description data to remove scenarios generated by models 
#' with a time horizon in 2050.
#'     
#' @param i_data the ar5data or a sub-selection of ar5data.
#' 
#' @return A quitte object containing the baseline scenarios. 
#' 
#' @examples
#' myData <- ar5rm_2050models()
#' 
#' @author Jerome Hilaire \email{hilaire@@pik-potsdam.de}
#' 
#' @keywords models, 2050, remove
#' 
#' @import dplyr tidyr
#' @export


ar5rm_2050models <- function(i_data=NULL) {
  
  if (is.null(i_data)) i_data <- ar5data    
  
  # Remove 2050 models
  o_sel <- i_data %>%
    filter(!model %in% unique(ar5scen$model[which(ar5scen$climate == "N/A")]))
  
  return(o_sel)
}